name = "MACEModels"
uuid = "29bafc4c-4f38-420f-a153-8a5a5e0bd5f6"
authors = ["Alexander Spears <alexander.spears@warwick.ac.uk> and contributors"]
version = "1.5.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DLPack = "53c2dc0f-f7d5-43fd-8906-6c0220547083"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
NQCBase = "78c76ebc-5665-4934-b512-82d81b5cbfb7"
NQCModels = "c814dc9f-a51f-4eaf-877f-82eda4edad48"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
CondaPkg = "0.2"
DLPack = "0.3"
NQCBase = "1"
NQCDInterfASE = "1"
NQCDynamics = "1"
NQCModels = "1"
ProgressMeter = "1"
PythonCall = "0.9"
SciMLBase = "2"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1"

[sources]
NQCDInterfASE = {url="https://github.com/NQCD/NQCDInterfASE.jl.git",rev="structure-type"}
NQCDynamics = {url="https://github.com/NQCD/NQCDynamics.jl.git",rev="main"}

[extras]
NQCDInterfASE = "4606675f-2246-4a0b-99d5-75b910de637b"
NQCDynamics = "36248dfb-79eb-4f4d-ab9c-e29ea5f33e14"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NQCDInterfASE", "NQCDynamics", "ProgressMeter"]
