name = "MACEModel"
uuid = "29bafc4c-4f38-420f-a153-8a5a5e0bd5f6"
authors = ["Alexander Spears <alexander.spears@warwick.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
